language: node_js
sudo: false
node_js:
  - '0.12'

install:
  - npm install hexo-cli -g
  - npm install

script:
  - git clone -b master https://${token}@github.com/lichunqiang/b public
  - hexo g
  - git config --global user.name "lichunqiang"
  - git config --global user.email "light-li@hotmail.com"
  - cd public
  - git add --all
  # - git commit -m `$(echo `date "+Site updated %Y-%m-%d %H:%M:%S"`)`
  # - git commit -m '$(curl -s http://whatthecommit.com/index.txt)'
  - git commit -m "$(curl -s http://whatthecommit.com/ | awk '/<p>/ {sub("<p>", ""); print }')"
  - git push -f origin master
