language: node_js
sudo: false
node_js:
  - 5.3.0

install:
  - npm install hexo-cli -g

script:
  - git clone -b master https://${token}@github.com/lichunqiang/b
  - cd b
  - npm install
  - hexo g
  - git config --global user.name "lichunqiang"
  - git config --global user.email "light-li@hotmail.com"
  - cd public
  - git add --all
  - git commit -m `$(echo `travis-ci "+Site updated %Y-%m-%d %H:%M:%S"`)`
  - git remote add origin https://${token}@github.com/lichunqiang/lichunqiang@github.io
  - git push -f origin master
