language: node_js
sudo: false
node_js:
  - 5.3.0

before_install:
  - git config --global user.name "lichunqiang"
  - git config --global user.email "light-li@hotmail.com"
  - git config --global push.default simple

install:
  - npm install hexo-cli -g

script:
  - git clone https://${token}@github.com/lichunqiang/lichunqiang.github.io.git .deploy_git -v
  - git --version
  - git remote add -f b https://${token}@github.com/lichunqiang/b.git
  - git fetch b
  - npm install

  - hexo g
  - cp -r public/* .deploy_git/
  - cd .deploy_git
  - git add -A
  - git commit -am "Auto deploy from Travis-CI."
  - git push --force -q
